
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 59399
 */
public class ComparacionNumerica extends javax.swing.JFrame {

    /**
     * Creates new form ComparacionNumerica
     */
    public ComparacionNumerica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNumero1 = new javax.swing.JLabel();
        txtIngresarnumero2 = new javax.swing.JTextField();
        btnComprobarPerfecto = new javax.swing.JButton();
        btnPrimo = new javax.swing.JButton();
        btnSumatoria = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        lblMensaje1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 204, 204)));

        lblTitulo.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblTitulo.setText("Comparación Númerica");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        lblNumero1.setBackground(new java.awt.Color(0, 153, 153));
        lblNumero1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblNumero1.setText("Ingrese un número: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumero1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        btnComprobarPerfecto.setBackground(new java.awt.Color(0, 204, 204));
        btnComprobarPerfecto.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnComprobarPerfecto.setText("Perfecto");
        btnComprobarPerfecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarPerfectoActionPerformed(evt);
            }
        });

        btnPrimo.setBackground(new java.awt.Color(0, 204, 204));
        btnPrimo.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnPrimo.setText("Primo");
        btnPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimoActionPerformed(evt);
            }
        });

        btnSumatoria.setBackground(new java.awt.Color(0, 204, 204));
        btnSumatoria.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnSumatoria.setText("Sumatoria");
        btnSumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumatoriaActionPerformed(evt);
            }
        });

        btnRaiz.setBackground(new java.awt.Color(0, 204, 204));
        btnRaiz.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnRaiz.setText("Raíz");
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        lblMensaje.setBackground(new java.awt.Color(204, 255, 204));
        lblMensaje.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lblMensaje.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMensaje1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lblMensaje1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(txtIngresarnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRaiz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSumatoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(btnPrimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnComprobarPerfecto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIngresarnumero2))
                .addGap(33, 33, 33)
                .addComponent(btnComprobarPerfecto)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrimo)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnSumatoria))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblMensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(btnRaiz)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprobarPerfectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarPerfectoActionPerformed
        // TODO add your handling code here:
        
    int n1 = Integer.parseInt(txtIngresarnumero2.getText()); 
    
    //Rango entre 1 al 500
     if (n1 < 1 || n1 > 500){ //El ciclo if verifica dos condición de que el numero ingresado "n1" sea menor a 1 y "n1" menor que 500
        lblMensaje1.setText("El número ingresado debe estar entre 1 y 500");  
    }
     //Indique si un número es perfecto//
    int sumaDivisores = 0; // Declara una variable sumaDivisores que sea inicia con el valor 0
    for (int i = 1; i <= n1 / 2; i++) { //Inicia el bucle for, declara la variable "i" con entero 
        // que itera desde 1, la iteración verifica i sea es mayor o igual a 1 y que el numero igresado sea divisible para 2
        if (n1 % i == 0) { //Verifica que n1 sea divible para i igualando a 0
        sumaDivisores += i; // Se acumula la suma de los divisores de n1
        }//cierra el ciclo if
    }//cierra el cliclo for
        if (sumaDivisores == n1) { //Verifica si la variable sumaDivisores es igual n1
            lblMensaje.setText("El número es perfecto");
        } else {
            lblMensaje.setText("El número no es perfecto");
        }
    }//GEN-LAST:event_btnComprobarPerfectoActionPerformed
 
    private void btnSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumatoriaActionPerformed
        // TODO add your handling code here:
        int n1 = Integer.parseInt(txtIngresarnumero2.getText());
        int suma = 0; 
        boolean esPrimo = true; // La variable esPrimo es igual a verdadera hasta que no se cumpla la condición de que el numero no es primo
        if (n1 >= 500) { //El ciclo if verifica que n1 se menor o igual a 500 que es el numero maximo 
            
            //Calcular la suma de numeros menore n1
            for(int i =2; i < n1; i++){// Dentro del bucle for se verifica que i sea igual a 2 y mientras i sea menor que n1 y va aumentando 1
              suma += i; //En la variable suma se almacena la suma de los numeros desde 2 hasta n1 (que es el numero ingresado)
                if (n1 % i == 0){//Verifica que n1 sea divible para i igualando a 0
                    esPrimo = false; //Si se encuentra que n1 es divisible para 1, se establese la variable esPrimo como falso, e indicando que no es primo                        break;
                }  
                lblMensaje1.setText("La suma primos números menores " +n1+ " es: " +suma);
            }
          
    }//GEN-LAST:event_btnSumatoriaActionPerformed
}
    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        // TODO= add your handling code here:
        int n1 = Integer.parseInt(txtIngresarnumero2.getText());
        
        if (n1 <= 500){// se esta indicando que n1 sea menor o igual a 500 
            double raizCuadrada = Math.sqrt (n1); //se utiliza un metodo de la clase math para calcular la raiz de n1 en la variable raizCuadrada
        lblMensaje1.setText("La raiz Cuadrada de " + n1 + " es: " + raizCuadrada);
    }//GEN-LAST:event_btnRaizActionPerformed
 }

    private void btnPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimoActionPerformed
       int n1 = Integer.parseInt(txtIngresarnumero2.getText());
       boolean esPrimo = true; // Se utiliza para determinar n1 sea primo y conste como verdadero caso contrario sera falso indicando que no es primo
       
       for (int i = 2; i <= Math.sqrt(n1); i++) {//En el bucle esta verificando si n1 es primo, itera desde 2 hasta la raiz cuadrada de n1
        //Si n1 es divisible por algun numero entre 2 y la raiz cuadrada de n1, entonces no es primo y termina el bucle
           if (n1 % i == 0) {
          break;
        }
    }
       if (esPrimo){
           StringBuilder primosMenores = new StringBuilder();// se crea un objeto SB llamado primosMenores, es util para concatenacion de catenas
           
        for (int i = 2; i < n1; i++) {
            if (esPrimo) {
            primosMenores.append(i).append(", ");// Si esPrimo es verdadero, el objeto se utiliza para almacenar y construir una cadena de numeros primos menores que n1 
        }
    }
        if (esPrimo){
            lblMensaje.setText("El número es primo");
            }else{
            lblMensaje.setText("El número es no primo");
            }
            lblMensaje1.setText("Primos menores: "+ primosMenores);    
        }       
    }//GEN-LAST:event_btnPrimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComparacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComparacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComparacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComparacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComparacionNumerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobarPerfecto;
    private javax.swing.JButton btnPrimo;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnSumatoria;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblNumero1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtIngresarnumero2;
    // End of variables declaration//GEN-END:variables

    private boolean numeroPerfecto(int n1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private int sumaPrimosMenores(int n1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private boolean primo(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private int esPrimo(int n1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
